master:
  image:
    eviles/mariadb-galera
  hostname:
    master
  environment:
    - NEW_CLUSTER=1
    - CLUSTER_NAME=local-test
    - CLUSTER=master
  volumes:
   - ./server.cnf:/etc/my.cnf.d/server.cnf
   - ./master:/var/lib/mysql
db2:
  image:
    eviles/mariadb-galera
  hostname:
    db2
  environment:
    - CLUSTER_NAME=local-test
    - CLUSTER=master
  volumes:
    - ./server.cnf:/etc/my.cnf.d/server.cnf
    - ./db2:/var/lib/mysql
  links:
    - master
db3:
  image:
    eviles/mariadb-galera
  hostname:
    db3
  environment:
    - CLUSTER_NAME=local-test
    - CLUSTER=master
  volumes:
    - ./server.cnf:/etc/my.cnf.d/server.cnf
    - ./db3:/var/lib/mysql
  links:
    - master
